Algoritmo "exPara"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 1000 ate 1500 passo 1 faca
  se ( cont mod 2 = 1 ) entao
      escreval ( cont )
  fimse
fimpara

Fimalgoritmo