Algoritmo "QUETAO06"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
// Seção de Declarações das variáveis
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 0

para cont de 0 ate 10 passo 1 faca
escreval ( cont, " elevado a 2 = ", (cont^2))
fimpara

Fimalgoritmo