Algoritmo "questao04"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
// Seção de Declarações das variáveis
cont, n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 1

escreval ("Digite um número para a realização de uma tabuada: ")
leia (n)

para cont de 0 ate 10 passo 1 faca
     escreval ( n, " X ", cont, " = ", ( n * cont ))

fimpara

Fimalgoritmo