Algoritmo "semnome"
//  
//  
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/11/2023
Var
// Seção de Declarações das variáveis
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 5


para cont de 5 ate 49 passo 1 faca

se  ( cont mod 5 = 0 ) entao
escreval ( cont)

fimse
fimpara
Fimalgoritmo