Algoritmo "questao04"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
// Seção de Declarações das variáveis
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Exibindo os números que existem no intervalo de 300 a 500")
cont <- 300
enquanto ( cont <= 500  ) faca
escreval(cont)
cont <- cont + 1

fimenquanto

Fimalgoritmo