Algoritmo "questao02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
num : inteiro

Inicio
      escreval("Informe um número: ")
      leia(num)

escolha(num)
     caso 1
          escreval("Bom dia!")
     caso 2
          escreval("Boa tarde!")
     caso 3
           escreval("Boa noite!")
     outrocaso
           escreval("Tchau!")

 fimescolha

Fimalgoritmo