Algoritmo "questao05"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
// Seção de Declarações das variáveis
cont, a: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 20
     repita
       a <- a + cont
       cont <- cont + 1
     ate ( cont > 70 )
escreval("A soma dos números no intervalo de 20 a 70 é de: ", a)

Fimalgoritmo